# Generated by Django 2.0.3 on 2018-11-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graintest',
            name='unit',
            field=models.CharField(default='kg', max_length=255),
        ),
    ]
